<?php

namespace AppBundle\Repository;

/**
 * DecisionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecisionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
